apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
data:   
  index.html: |
    <!DOCTYPE html>
    <html>
      <body style="background-color: #F00">
        <h1>I've been deployed Development</h1>
      </body>
    </html>