apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx-svc
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: od-nginx-development
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: nginx
